
services:
  serverAbatJour:
    container_name: serverAbatJour
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file: .env
    ports:
      - $NODE_PORT:$NODE_PORT
    # variable d'environment pour permettre de confirgurer l'acces du server à mongo
    environment:
        - MONGODB_URL=mongodb://mongodb:27017/AbatJourImpromptu
        - ENV_TYPE=dev
        - DEV_URL=http://localhost:5173
    stdin_open: true
    tty: true
    cap_drop:
      - ALL
    command: ["nodemon", "--legacy-watch", "server.js"]


  # mongodb:
  #   image: mongo:7
  #   container_name: mongodb
  #   restart: unless-stopped
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./mongo-data:/data/db
  #   networks: 
  #     - server
# volumes:
#   mongo-data:

